import { ExchangeInfoData } from "@/types/binance";

export const mockExchangeInfoData: ExchangeInfoData = {
  exchangeFilters: [],
  rateLimits: [],
  serverTime: Date.now(),
  symbols: [
    {
      symbol: "BTCUSDT",
      status: "TRADING" as const,
      baseAsset: "BTC",
      quoteAsset: "USDT",
      baseAssetPrecision: 8,
      quotePrecision: 8,
      quoteAssetPrecision: 8,
      baseCommissionPrecision: 8,
      quoteCommissionPrecision: 8,
      orderTypes: ["LIMIT" as const, "MARKET" as const],
      icebergAllowed: false,
      ocoAllowed: false,
      otoAllowed: false,
      opoAllowed: false,
      quoteOrderQtyMarketAllowed: false,
      allowTrailingStop: false,
      cancelReplaceAllowed: false,
      amendAllowed: false,
      pegInstructionsAllowed: false,
      isSpotTradingAllowed: true,
      isMarginTradingAllowed: false,
      filters: [],
      permissions: [],
      permissionSets: [],
      defaultSelfTradePreventionMode: "EXPIRE_TAKER" as const,
      allowedSelfTradePreventionModes: ["EXPIRE_TAKER" as const],
    },
    {
      symbol: "ETHUSDT",
      status: "TRADING" as const,
      baseAsset: "ETH",
      quoteAsset: "USDT",
      baseAssetPrecision: 8,
      quotePrecision: 8,
      quoteAssetPrecision: 8,
      baseCommissionPrecision: 8,
      quoteCommissionPrecision: 8,
      orderTypes: ["LIMIT" as const, "MARKET" as const],
      icebergAllowed: false,
      ocoAllowed: false,
      otoAllowed: false,
      opoAllowed: false,
      quoteOrderQtyMarketAllowed: false,
      allowTrailingStop: false,
      cancelReplaceAllowed: false,
      amendAllowed: false,
      pegInstructionsAllowed: false,
      isSpotTradingAllowed: true,
      isMarginTradingAllowed: false,
      filters: [],
      permissions: [],
      permissionSets: [],
      defaultSelfTradePreventionMode: "EXPIRE_TAKER" as const,
      allowedSelfTradePreventionModes: ["EXPIRE_TAKER" as const],
    },
  ],
  timezone: "UTC",
};
